# NOTE: these are the roles that won't recieve an automated
# message when the word 'download' is detected in a message
IgnoredRoles:
  - 801386133815951361 # @staff
  - 717144039568441394 # @Sublimer
  - 717144455156858940 # @Sapphirer
  - 717144765690282015 # @Steeler

# NOTE: Role that will be applied when someone is !muted
MuteRole: 777002205034971136

# NOTE: Roles that can use moderation commands
StaffRoles:
  - 717151202135113808 # @Admin
  - 801386133815951361 # @staff

# NOTE: Amount of time in seconds
# until an error message is deleted
ErrorMessageTimeout: 5

# NOTE: Amount of time in seconds from
# the bot adding the 🚫 reaction until
# the message gets auto-deleted.
ReactionTimeout: 5
