
# NOTE: Role that will be applied when someone is !muted
MuteRole: 798708529917460510

# NOTE: Bot token
botToken:

# NOTE: Team Stylized Server ID
guildID: 706624339595886683

# NOTE: Channel where the ModMail is sent
ModMailChannel: 799741426886901850

# NOTE: Roles that can use moderation commands
StaffRoles:
  - 706637341850206269 # @Admin
  - 799498278210109472 # @moderator

# NOTE: Amount of time in seconds
# until an error message is deleted
ErrorMessageTimeout: 5 #SECONDS

# NOTE: Amount of time in seconds from
# the bot adding the 🚫 reaction until
# the message gets auto-deleted.
ReactionTimeout: 5 #SECONDS

# NOTE: Cogs that will be loaded after the
# bot is connected to the discord API.
DelayedLoadCogs:
  - add
  - moderation
  - modmail
  - vcban
  - warn

# NOTE: Channel where game commands are sent
ConsoleCommandsChannel: 764631105097170974

# NOTE: Role to deny people access to VCs
VcBanRole: 858598967749902386
