# NOTE: these are the roles that won't recieve an automated
# message when the word 'download' is detected in a message
IgnoredRoles:
  - 801386133815951361 # @staff
  - 717144039568441394 # @Sublimer
  - 717144455156858940 # @Sapphirer
  - 717144765690282015 # @Steeler

# NOTE: Blackhole channel IDs
blackholes:
  - 863840701989257216
  - 863823582698405948

# NOTE: Role that will be applied when someone is !muted
MuteRole: 860648781594099733

# NOTE: Role to deny sending images to channels
noMediaRole: 860649799011139625

TicketsCategory: 864696316419506227
TicketsArchve: 864870736372301844
TicketStaffRole: 864737541726142474
TicketLogChannel: 864993238985474078

# NOTE: Role to deny sending URLs to channels
urlBanRole: none

# NOTE: Role to deny sending URLs to channels
BlackoutRole: 867110442489085953

blackout_channel: 867110401035993138

# NOTE: Bot token
botToken: ODYwNjI4NjkyMDgyNDkxMzky.YN-A7Q.doE8ftbPfJvGXZp_9kd3N_2284s

# NOTE: OSP server id
guildID: 831897006812561409

# NOTE: Channel where the StaffMail is sent
ModMailChannel: 860633218829778954

# NOTE: Roles that can use moderation commands
StaffRoles:
  - 860605908534427668 # @OSP Admin Team

# NOTE: Channel of the welcome messages
WelcomeChannel: 860610099541966929

# NOTE: Channel of the join-leave staff-log
JLLog: 860627866332561408

# NOTE: Rules channel, Verified Role and Unverified role
RulesReactionChannel: 860610234539835433
RulesUnvRole: 860609206453665792
RulesVerRole: 860609404093464586

# NOTE: Amount of time in seconds
# until an error message is deleted
ErrorMessageTimeout: 5 #SECONDS

# NOTE: Amount of time in seconds from
# the bot adding the 🚫 reaction until
# the message gets auto-deleted.
ReactionTimeout: 5 #SECONDS

# NOTE: Cogs that will be loaded after the
# bot is connected to the discord API.
DelayedLoadCogs:
  - modmail
  - moderation
  - events
  - test
  - tickets

safe_urls:
  - cdn.discordapp.com
  - media.discordapp.net
  - ptb.discord.com
  - canary.discord.com
  - discord.com
  - dis.gd
  - www.dis.gd
  - www.youtube.com
  - youtube.com
  - m.youtube.com
  - youtu.be
  - i.imgur.com
  - imgur.com
  - www.imgur.com
  - discord.gift
  - www.java.com
  - java.com
  - www.spigotmc.org
  - spigotmc.org
  - vm.tiktok.com
  - dev.bukkit.org
  - www.curseforge.com
  - curseforge.com
  - github.com
  - www.github.com
  - google.com
  - www.google.com
  - docs.google.com
  - www.patreon.com
  - patreon.com
  - drive.google.com
  - www.stylizedresourcepack.com
  - stylizedresourcepack.com
  - c.tenor.com
  - tenor.com
  - www.tenor.com
  - bitslablab.com
  - www.bitslablab.com
