"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from .main import load_dotenv

def load_ipython_extension(ipython: Any) -> None: ...
def get_cli_string(
    path: Optional[str] = ...,
    action: Optional[str] = ...,
    key: Optional[str] = ...,
    value: Optional[str] = ...,
    quote: Optional[str] = ...,
) -> str:
    """Returns a string suitable for running as a shell script.

    Useful for converting a arguments passed to a fabric task
    to be passed to a `local` or `run` command.
    """
    ...

__all__ = ['get_cli_string', 'load_dotenv', 'load_ipython_extension']
