"""
This type stub file was generated by pyright.
"""

import os
from typing import IO, Optional, Union

def load_dotenv(
    dotenv_path: Union[str, os.PathLike[str], None] = ...,
    stream: Optional[IO[str]] = ...,
    verbose: bool = ...,
    override: bool = ...,
    interpolate: bool = ...,
    encoding: Optional[str] = ...,
) -> bool:
    """Parse a .env file and then load all the variables found as environment variables.

    Parameters:
        dotenv_path: Absolute or relative path to .env file.
        stream: Text stream (such as `io.StringIO`) with .env content, used if
            `dotenv_path` is `None`.
        verbose: Whether to output a warning the .env file is missing.
        override: Whether to override the system environment variables with the variables
            from the `.env` file.
        encoding: Encoding to be used to read the file.
    Returns:
        Bool: True if atleast one environment variable is set elese False

    If both `dotenv_path` and `stream` are `None`, `find_dotenv()` is used to find the
    .env file.
    """
    ...
