"""
This type stub file was generated by pyright.
"""

"""
parsedatetime/warns.py

All subclasses inherited from `Warning` class

"""
class pdtDeprecationWarning(DeprecationWarning):
    ...


class pdtPendingDeprecationWarning(PendingDeprecationWarning):
    ...


class pdt20DeprecationWarning(pdtPendingDeprecationWarning):
    ...


